### ISSUE TITLE
remove mootools dependence

### ISSUE THREAD

**Issue by clindsey** [oampo/Audiolet#1]
I don't want to use mootools/jquery/prototype for some projects

**Comment by oampo** [comment]
Audiolet depends very heavily on Mootools' class system, so it's not trivial to decouple the two.  If the full Mootools distribution is too heavy then as far as I know you can replace it with a build from http://mootools.net/core/ which only contains Class and it's dependencies.  I'll be happy to have a look at a patch which replicates the Mootools functionality which is used, but for now it seems like it would be unnecessary duplication of effort for very little gain.

**Comment by oampo** [comment]
Audiolet is now MooTools free in master.
