### ISSUE TITLE
Skipping in Chrome

### ISSUE THREAD

**Issue by baffo32** [oampo/Audiolet#13]
The basic sine example does not play properly for me in Chrome 14.0.835.186, Windows 7 64-bit.  It begins skipping after just a second or two.  I have the same issue with any other continuous sound from Audiolet.

The sink.js tests all perform fine for me.

**Comment by baffo32** [comment]
Sorry; closed this thinking it was a small bug in sink.js .  Seems to be some timing issue; if I set a breakpoint, the skips go away.

**Comment by oampo** [comment]
Yeah, I know about this - it's related to http://code.google.com/p/chromium/issues/detail?id=82795.  I think there are some changes to the audio backend in Chrome on their way which will hopefully sort it out.  For now I think you can just set a small timeout before creating the Audiolet object, but YMMV with this.  Anyway, I'll leave this bug open until there is a more sensible fix available.

**Comment by baffo32** [comment]
That helps a lot!

It seems this is happening because the Audiolet object is getting garbage collected.  This works fine:

var audiolet;
window.onload = function() {
    audiolet = new Audiolet();
    var sine = new Sine(audiolet);
    sine.connect(audiolet.output);
};

**Comment by baffo32** [comment]
Relevant: https://github.com/jussi-kalliokoski/sink.js/pull/3

**Comment by oampo** [comment]
Thanks for properly tracking this down @baffo32 - I really didn't fully understand what was getting GCed here.  Also cheers for the typo fixes in the documentation.  Glad to see someone's actually reading them :)
