### ISSUE TITLE
Disconnecting - what am I doing wrong?

### ISSUE THREAD

**Issue by qdotme** [oampo/Audiolet#2]
```
var audiolet = new Audiolet();
var sine = new Sine(audiolet, 440);
sine.connect(audiolet.output);
sine.disconnect(audiolet.output);
```

I'm getting the 'inputPin is undefined' error.

Do you have any example of disconnecting nodes?

**Comment by oampo** [comment]
Oops, this is a bug - I missed out a default argument for the input pin.  Fixed in oampo/Audiolet@b3dddee793c79e57a7426b202a60e7b0f50977e4

Thanks for the report,
Joe
