### ISSUE TITLE
Limiter example?

### ISSUE THREAD

**Issue by msonnabaum** [oampo/Audiolet#20]
I've played around with the Limiter, but can't seem to get it to do much. I'd be great to have an example of it's proper usage.

**Comment by oampo** [comment]
Sorry about this - there was a frankly stupendous amount of fail in the Limiter code which should now be fixed.  Usage should be pretty simple, and the defaults are fairly good as a standard - something like this should work fine now:

``` javascript
   var audiolet = new Audiolet();
   var synth = new MyVeryLoudSynth(audiolet);
   var threshold = 0.95, attack = 0.01, release = 0.4; // Default values, attack and release times given in seconds.
   var limiter = new Limiter(audiolet, threshold, attack, release);
   synth.connect(limiter);
   limiter.connect(audiolet.output);
```
