### ISSUE TITLE
Uncaught No audio sink available

### ISSUE THREAD

**Issue by stolinski** [oampo/Audiolet#24]
Pretty much any of the examples stop outputting audio and give the error "Uncaught No audio sink available" for Audiolet.min.js:257. Is this just a result of Chrome not fully supporting the audio api yet?

**Comment by oampo** [comment]
This is the same problem as issue #18, and is a bug with how the examples are set up.  Basically in real life as long as you don't create more than one Audiolet object you should be fine, so consider the examples as pretty much run once and then reload for now.  A bit of a snafu on my part though - I've made a new bug to track progress on fixing up the examples at #25.

**Comment by stolinski** [comment]
Ah sorry, I just noticed this! Thanks!
