### ISSUE TITLE
ADSREnvelope doesn't allow attack, etc. to be changed at runtime

### ISSUE THREAD

**Issue by rjmarsan** [oampo/Audiolet#31]
ADSREnvelope takes attack, decay, sustain, and release as constructor parameters, but doesn't allow them to be changed with setValue() at runtime, meaning if you want to vary any of those parameters, you must make a new envelope.

**Comment by oampo** [comment]
Yeah, this should definitely be possible.  You can now do something like env.attack.setValue(2).  Thanks for the report!
