### ISSUE TITLE
build and dist creating bad files

### ISSUE THREAD

**Issue by kn0ll** [oampo/Audiolet#37]
hi,

when i run ./build from the src dir without changing any files, it creates a new Audiolet.js file which differs from the distributed one. when i include it using the Sine example from the readme, i get this error:

`Uncaught ReferenceError: Sink is not defined Audiolet.js:707`

it seemed that the sink definition was non-existent in Audiolet.js. on a whim, i tried changing the globbing in the build file from `sink.js/*.js` to `sink.js/**/*.js`\- which actually resolved that issue (and included the Sink definition), but brought upon two new errors:

`Uncaught TypeError: Cannot set property 'EventEmitter' of undefined Audiolet.js:5715`
`Uncaught TypeError: Property 'Sink' of object [object Window] is not a function Audiolet.js:707`

i'd keep going down the rabbit hole trying to resolve it but i wanted to see if i was missing something? i am using juicer 1.0.16. thanks!

**Comment by oampo** [comment]
Cheers for the report.  Have updated the build script so it first builds sink.js, then builds Audiolet using that.
