### ISSUE TITLE
More node events

### ISSUE THREAD

**Issue by oampo** [oampo/Audiolet#49]
AudioletNodes should emit more events which are useful for GUIs.  Connect and disconnect are the obvious candidates.

**Comment by kn0ll** [comment]
added this as a piece of https://github.com/oampo/Audiolet/pull/47 in commit https://github.com/catshirt/Audiolet/commit/d6a7525c7a0700d5ac4778bfa87fc02af0da49ab

**Comment by oampo** [comment]
Cool, this has been pulled in now as part of #47, so can close.
